[topics.lexers]
name = "Lexers"
description = "Blah"

[topics.repl]
name = "Repl"
description = "Blah"

[topics.regex]
name = "Regular Expressions"
description = "Blah"

[[project]]
name = "logos"
topics = ["lexers"]

[[project]]
name = "lrlex"
topics = ["lexers"]

[[project]]
name = "rustyline"
topics = ["repl"]

[[project]]
name = "repl-rs"
topics = ["repl"]

[[project]]
name = "termwiz"
topics = ["repl"]