[topics.lexing]
name = "Lexing"
description = "to be written"

[topics.parsing]
name = "Parsing"
description = "to be written"

[topics.repl]
name = "REPL"
description = "REPLs are a common way to interact with compilers by executing code statement by statement."

[[project]]
name = "logos"
description = "Create ridiculously fast lexers."
repo = "https://github.com/maciejhirsz/logos"
crates = ["logos"]
topics = ["lexing"]

[[project]]
name = "lrlex"
description = "A partial replacement for lex/flex."
repo = "https://github.com/softdevteam/grmtools/tree/master/lrlex"
crates = ["lrlex"]
topics = ["lexing"]

[[project]]
name = "LALRPOP"
description = "A convenient LR(1) parser generator."
repo = "https://github.com/lalrpop/lalrpop"
crates = ["lalrpop", "lalrpop-util"]
docs = "https://lalrpop.github.io/lalrpop/"
topics = ["parsing"]

[[project]]
name = "chumsky"
description = " A parser library for humans with powerful error recovery."
repo = "https://github.com/zesterer/chumsky/"
crates = ["chumsky"]
docs = "https://github.com/zesterer/chumsky/blob/master/tutorial.md"
topics = ["parsing"]

[[project]]
name = "rustyline"
description = "A readline implementation in Rust."
repo = "https://github.com/kkawakam/rustyline"
crates = ["rustyline"]
topics = ["repl"]

[[project]]
name = "repl-rs"
description = "A library to generate a REPL for your application."
repo = "https://github.com/jacklund/repl-rs"
crates = ["repl-rs"]
topics = ["repl"]

[[showcase]]
name = "AbleScript"
description = "AbleScript is a procedural, cursed, dynamically-typed, interpreted programming language, designed to be bad."
repo = "https://git.ablecorp.us/AbleScript/able-script"
docs = "https://ablecorp.github.io/able-script-the-book/"
